# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08e1129365165a7d8cc3dc63502607bfb0f2cde663402e90a9f6959671f686b65609d454028e6971c6a1ef8d1b8035221f8585f11ac761c85048692d21811c93

test:
  secret_key_base: ddeeaf21cc255c5be718c5d0614830efab58ef18dd32f48ccfd79e0a20b63235bc70083b7318d50c0f51a8a065fd9d93b5bb163f735260412d15d597f9b72d58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
